name: Test Build Configurations

on:
  push:
    branches: ['build-test*']

defaults:
  run:
    shell: bash

jobs:
  Test:
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-latest, macos-10.15]
        env: [Linux, Windows, Mac]
        arch: [x64, x86]
        sound: [OFF, SDL_mixer]
        windowing: [Console, X11, GTK, SDL, Windows]
        debugrec: [OFF, ON]
        exclude:
          - os: ubuntu-18.04
            env: Mac
          - os: ubuntu-18.04
            env: Windows
          - os: windows-latest
            env: Mac
          - os: windows-latest
            env: Linux
          - os: macos-10.15
            env: Windows
          - os: macos-10.15
            env: Linux

          - arch: x86
            os: macos-10.15

          - os: windows-latest
            windowing: X11
          - os: macos-10.15
            windowing: X11
          - os: windows-latest
            windowing: GTK
          - os: macos-10.15
            windowing: GTK
          - os: macos-10.15
            windowing: Windows
          - os: ubuntu-18.04
            windowing: Windows

          - sound: SDL_mixer
            windowing: Console
          - debugrec: ON
            sound: OFF
          - debugrec: ON
            windowing: X11
          - debugrec: ON
            windowing: SDL
    env:
      PLATFORM: ${{ matrix.arch }}

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: "Configure Platform"
        run: |
          autobuild/${{ matrix.env }}.sh
          autobuild/${{ matrix.env }}-${{ matrix.arch }}.sh
          echo "CONFIG_SUFFIX=${{ matrix.env }}-${{ matrix.arch }}" >> $GITHUB_ENV

      - name: "Linux x86: Setup chroot"
        if: ${{ matrix.env == 'Linux' && matrix.arch == 'x86' }}
        run: |
          curl -L https://github.com/legacyclonk/ubuntu-1804-x86-chroot/releases/download/2020-09-26/chroot.tar.xz | sudo tar -xJ
          curl -L https://raw.githubusercontent.com/legacyclonk/ubuntu-1804-x86-chroot/master/setup_chroot.sh | sudo bash -e -
          sudo mkdir -p chroot/$PWD
          sudo mount --bind . chroot/$PWD

      - name: "Linux: Setup"
        if: ${{ matrix.env == 'Linux' }}
        run: $CHROOT autobuild/setup_linux.sh

      - name: "Mac: Work around libpng mess"
        if: ${{ matrix.env == 'Mac' }}
        run: sudo rm -r /Library/Frameworks/Mono.framework/Headers

      - name: "Windows: Setup VS Dev Environment"
        if: ${{ matrix.env == 'Windows' }}
        uses: seanmiddleditch/gha-setup-vsdevenv@v3
        with:
          arch: ${{ env.VS_ARCH }}

      - name: "Dependencies"
        run: |
          mkdir deps
          cd deps
          curl -L https://github.com/legacyclonk/deps/releases/download/2021-03-12/lc_deps-$CONFIG_SUFFIX.tar.gz | tar -xz

      - name: Configure
        run: |
          $CHROOT cmake -B build . $CMAKE_CONFIGURE_ARGS

      - name: "Configuration setup: No Sound"
        if: ${{ matrix.sound == 'OFF' }}
        run: $CHROOT cmake -B build -DENABLE_SOUND=Off

      - name: "Configuration setup: SDL_mixer"
        if: ${{ matrix.sound == 'SDL_mixer' }}
        run: $CHROOT cmake -B build -DUSE_SDL_MIXER=On

      - name: "Configuration setup: Console"
        if: ${{ matrix.windowing == 'Console' }}
        run: $CHROOT cmake -B build -DUSE_CONSOLE=On

      - name: "Configuration setup: GTK"
        if: ${{ matrix.windowing == 'GTK' }}
        run: $CHROOT cmake -B build -DWITH_DEVELOPER_MODE=On

      - name: "Configuration setup: SDL"
        if: ${{ matrix.windowing == 'SDL' }}
        run: $CHROOT cmake -B build -DUSE_SDL_MAINLOOP=On -DWITH_DEVELOPER_MODE=Off

      - name: "Configuration setup: X11"
        if: ${{ matrix.windowing == 'X11' }}
        run: $CHROOT cmake -B build -DWITH_DEVELOPER_MODE=Off

      - name: Build
        run: |
          $CHROOT cmake --build build -v $CMAKE_BUILD_ARGS

